### ISSUE TITLE
[REQUEST] Update to Twig 2.x

### ISSUE THREAD

**Issue by B0bbyD0llar** [thePanz/Twig-Extension-Number#4]
Hi,

is it possible to update this package to work with twig 2.x?

**Comment by thePanz** [comment]
Hi @B0bbyD0llar, still no plans to support Twig 2.x.
The implementation should already support it, as I did not use any deprecated functions from latest 1.x release.
Could you give it a try with twig 2.x and report any issue you get? Thank you :)

**Comment by thePanz** [comment]
Initial twig 2.x support added in #5 , can you test it? I'll tag a new release if it works fine for you, too :)

**Comment by TiGR** [comment]
It works fine for me here, I think you can tag it.

**Comment by thePanz** [comment]
Thanks @TiGR 
Version 1.1.0 tagged https://github.com/thePanz/Twig-Extension-Number/releases/tag/1.1.0 (\cc @B0bbyD0llar )
